# random module = module that generates random numbers
# pseudo-random numbers = numbers that appear to be random but are actually generated by a formula

import random

x = random.randint(1,6)
print(x)

y = random.random()
print(y)

myList = ["rock", "paper", "scissors"]
z = random.choice(myList)

cards = ["ace",2,3,4,5,6,7,8,9,10,"jack","queen","king"]
random.shuffle(cards)
print(cards)
